package scs.demos.philosopher;

/**
* scs/demos/philosopher/PhilosopherHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/philosopher.idl
* Saturday, October 18, 2008 4:06:49 PM BRST
*/

public final class PhilosopherHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.demos.philosopher.Philosopher value = null;

  public PhilosopherHolder ()
  {
  }

  public PhilosopherHolder (scs.demos.philosopher.Philosopher initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.demos.philosopher.PhilosopherHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.demos.philosopher.PhilosopherHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.demos.philosopher.PhilosopherHelper.type ();
  }

}
