package scs.demos.philosopher;

/**
* scs/demos/philosopher/PhilosopherStateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/philosopher.idl
* Saturday, October 18, 2008 4:06:49 PM BRST
*/

public final class PhilosopherStateHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.demos.philosopher.PhilosopherState value = null;

  public PhilosopherStateHolder ()
  {
  }

  public PhilosopherStateHolder (scs.demos.philosopher.PhilosopherState initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.demos.philosopher.PhilosopherStateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.demos.philosopher.PhilosopherStateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.demos.philosopher.PhilosopherStateHelper.type ();
  }

}
