package scs.demos.philosopher;


/**
* scs/demos/philosopher/PhilosopherState.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/philosopher.idl
* Saturday, October 18, 2008 4:06:49 PM BRST
*/

public class PhilosopherState implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 5;
  private static scs.demos.philosopher.PhilosopherState[] __array = new scs.demos.philosopher.PhilosopherState [__size];

  public static final int _EATING = 0;
  public static final scs.demos.philosopher.PhilosopherState EATING = new scs.demos.philosopher.PhilosopherState(_EATING);
  public static final int _THINKING = 1;
  public static final scs.demos.philosopher.PhilosopherState THINKING = new scs.demos.philosopher.PhilosopherState(_THINKING);
  public static final int _HUNGRY = 2;
  public static final scs.demos.philosopher.PhilosopherState HUNGRY = new scs.demos.philosopher.PhilosopherState(_HUNGRY);
  public static final int _STARVING = 3;
  public static final scs.demos.philosopher.PhilosopherState STARVING = new scs.demos.philosopher.PhilosopherState(_STARVING);
  public static final int _DEAD = 4;
  public static final scs.demos.philosopher.PhilosopherState DEAD = new scs.demos.philosopher.PhilosopherState(_DEAD);

  public int value ()
  {
    return __value;
  }

  public static scs.demos.philosopher.PhilosopherState from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected PhilosopherState (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class PhilosopherState
