package scs.demos.philosopher;


/**
* scs/demos/philosopher/StatusInfoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/philosopher.idl
* Saturday, October 18, 2008 4:06:49 PM BRST
*/

abstract public class StatusInfoHelper
{
  private static String  _id = "IDL:scs/demos/philosopher/StatusInfo:1.0";

  public static void insert (org.omg.CORBA.Any a, scs.demos.philosopher.StatusInfo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static scs.demos.philosopher.StatusInfo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "name",
            _tcOf_members0,
            null);
          _tcOf_members0 = scs.demos.philosopher.PhilosopherStateHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "state",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulong);
          _members0[2] = new org.omg.CORBA.StructMember (
            "ticks_since_last_meal",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[3] = new org.omg.CORBA.StructMember (
            "has_left_fork",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[4] = new org.omg.CORBA.StructMember (
            "has_right_fork",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (scs.demos.philosopher.StatusInfoHelper.id (), "StatusInfo", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static scs.demos.philosopher.StatusInfo read (org.omg.CORBA.portable.InputStream istream)
  {
    scs.demos.philosopher.StatusInfo value = new scs.demos.philosopher.StatusInfo ();
    value.name = istream.read_string ();
    value.state = scs.demos.philosopher.PhilosopherStateHelper.read (istream);
    value.ticks_since_last_meal = istream.read_ulong ();
    value.has_left_fork = istream.read_boolean ();
    value.has_right_fork = istream.read_boolean ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, scs.demos.philosopher.StatusInfo value)
  {
    ostream.write_string (value.name);
    scs.demos.philosopher.PhilosopherStateHelper.write (ostream, value.state);
    ostream.write_ulong (value.ticks_since_last_meal);
    ostream.write_boolean (value.has_left_fork);
    ostream.write_boolean (value.has_right_fork);
  }

}
