package scs.instrumentation;

/**
* scs/instrumentation/InterfaceStatsNotAvailableHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.instrumentation.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public final class InterfaceStatsNotAvailableHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.instrumentation.InterfaceStatsNotAvailable value = null;

  public InterfaceStatsNotAvailableHolder ()
  {
  }

  public InterfaceStatsNotAvailableHolder (scs.instrumentation.InterfaceStatsNotAvailable initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.instrumentation.InterfaceStatsNotAvailableHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.instrumentation.InterfaceStatsNotAvailableHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.instrumentation.InterfaceStatsNotAvailableHelper.type ();
  }

}
