package scs.instrumentation;


/**
* scs/instrumentation/IOStatsNotAvailable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.instrumentation.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public final class IOStatsNotAvailable extends org.omg.CORBA.UserException
{

  public IOStatsNotAvailable ()
  {
    super(IOStatsNotAvailableHelper.id());
  } // ctor


  public IOStatsNotAvailable (String $reason)
  {
    super(IOStatsNotAvailableHelper.id() + "  " + $reason);
  } // ctor

} // class IOStatsNotAvailable
