package scs.instrumentation;


/**
* scs/instrumentation/MethodStatsSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.instrumentation.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

abstract public class MethodStatsSeqHelper
{
  private static String  _id = "IDL:scs/instrumentation/MethodStatsSeq:1.0";

  public static void insert (org.omg.CORBA.Any a, scs.instrumentation.MethodStats[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static scs.instrumentation.MethodStats[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = scs.instrumentation.MethodStatsHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (scs.instrumentation.MethodStatsSeqHelper.id (), "MethodStatsSeq", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static scs.instrumentation.MethodStats[] read (org.omg.CORBA.portable.InputStream istream)
  {
    scs.instrumentation.MethodStats value[] = null;
    int _len0 = istream.read_long ();
    value = new scs.instrumentation.MethodStats[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = scs.instrumentation.MethodStatsHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, scs.instrumentation.MethodStats[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      scs.instrumentation.MethodStatsHelper.write (ostream, value[_i0]);
  }

}
