package scs.instrumentation;


/**
* scs/instrumentation/StatsCollectionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.instrumentation.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

abstract public class StatsCollectionHelper
{
  private static String  _id = "IDL:scs/instrumentation/StatsCollection:1.0";

  public static void insert (org.omg.CORBA.Any a, scs.instrumentation.StatsCollection that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static scs.instrumentation.StatsCollection extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (scs.instrumentation.StatsCollectionHelper.id (), "StatsCollection");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static scs.instrumentation.StatsCollection read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_StatsCollectionStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, scs.instrumentation.StatsCollection value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static scs.instrumentation.StatsCollection narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof scs.instrumentation.StatsCollection)
      return (scs.instrumentation.StatsCollection)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      scs.instrumentation._StatsCollectionStub stub = new scs.instrumentation._StatsCollectionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static scs.instrumentation.StatsCollection unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof scs.instrumentation.StatsCollection)
      return (scs.instrumentation.StatsCollection)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      scs.instrumentation._StatsCollectionStub stub = new scs.instrumentation._StatsCollectionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
