package scs.instrumentation;

/**
* scs/instrumentation/SystemNetworkStatsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.instrumentation.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public final class SystemNetworkStatsHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.instrumentation.SystemNetworkStats value = null;

  public SystemNetworkStatsHolder ()
  {
  }

  public SystemNetworkStatsHolder (scs.instrumentation.SystemNetworkStats initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.instrumentation.SystemNetworkStatsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.instrumentation.SystemNetworkStatsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.instrumentation.SystemNetworkStatsHelper.type ();
  }

}
