package scs.instrumentation;


/**
* scs/instrumentation/SystemNetworkStatsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.instrumentation.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

abstract public class SystemNetworkStatsHelper
{
  private static String  _id = "IDL:scs/instrumentation/SystemNetworkStats:1.0";

  public static void insert (org.omg.CORBA.Any a, scs.instrumentation.SystemNetworkStats that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static scs.instrumentation.SystemNetworkStats extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulonglong);
          _members0[0] = new org.omg.CORBA.StructMember (
            "bytesReceived",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulonglong);
          _members0[1] = new org.omg.CORBA.StructMember (
            "bytesTransmitted",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (scs.instrumentation.SystemNetworkStatsHelper.id (), "SystemNetworkStats", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static scs.instrumentation.SystemNetworkStats read (org.omg.CORBA.portable.InputStream istream)
  {
    scs.instrumentation.SystemNetworkStats value = new scs.instrumentation.SystemNetworkStats ();
    value.bytesReceived = istream.read_ulonglong ();
    value.bytesTransmitted = istream.read_ulonglong ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, scs.instrumentation.SystemNetworkStats value)
  {
    ostream.write_ulonglong (value.bytesReceived);
    ostream.write_ulonglong (value.bytesTransmitted);
  }

}
