package scs.demos.pingpong;


/**
* scs/demos/pingpong/PingPong.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/pingPong.idl
* Saturday, October 18, 2008 4:06:49 PM BRST
*/

public interface PingPong extends PingPongOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PingPong
