package scs.event_service;


/**
* scs/event_service/ChannelCollectionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/events.idl
* Saturday, October 18, 2008 4:06:47 PM BRST
*/

public abstract class ChannelCollectionPOA extends org.omg.PortableServer.Servant
 implements scs.event_service.ChannelCollectionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getChannel", new java.lang.Integer (0));
    _methods.put ("getAll", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // scs/event_service/ChannelCollection/getChannel
       {
         String name = in.read_string ();
         scs.core.IComponent $result = null;
         $result = this.getChannel (name);
         out = $rh.createReply();
         scs.core.IComponentHelper.write (out, $result);
         break;
       }

       case 1:  // scs/event_service/ChannelCollection/getAll
       {
         scs.event_service.ChannelDescr $result[] = null;
         $result = this.getAll ();
         out = $rh.createReply();
         scs.event_service.ChannelDescrSeqHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:scs/event_service/ChannelCollection:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ChannelCollection _this() 
  {
    return ChannelCollectionHelper.narrow(
    super._this_object());
  }

  public ChannelCollection _this(org.omg.CORBA.ORB orb) 
  {
    return ChannelCollectionHelper.narrow(
    super._this_object(orb));
  }


} // class ChannelCollectionPOA
