package scs.event_service;


/**
* scs/event_service/ChannelDescrSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/events.idl
* Saturday, October 18, 2008 4:06:47 PM BRST
*/

public final class ChannelDescrSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.event_service.ChannelDescr value[] = null;

  public ChannelDescrSeqHolder ()
  {
  }

  public ChannelDescrSeqHolder (scs.event_service.ChannelDescr[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.event_service.ChannelDescrSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.event_service.ChannelDescrSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.event_service.ChannelDescrSeqHelper.type ();
  }

}
