package scs.event_service;


/**
* scs/event_service/ChannelManagementPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/events.idl
* Saturday, October 18, 2008 4:06:47 PM BRST
*/

public abstract class ChannelManagementPOA extends org.omg.PortableServer.Servant
 implements scs.event_service.ChannelManagementOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("subscribeChannel", new java.lang.Integer (0));
    _methods.put ("cancelChannel", new java.lang.Integer (1));
    _methods.put ("notifyChannel", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // scs/event_service/ChannelManagement/subscribeChannel
       {
         String clientName = in.read_string ();
         String channelName = in.read_string ();
         scs.event_service.EventSink sink = scs.event_service.EventSinkHelper.read (in);
         boolean $result = false;
         $result = this.subscribeChannel (clientName, channelName, sink);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // scs/event_service/ChannelManagement/cancelChannel
       {
         String clientName = in.read_string ();
         String channelName = in.read_string ();
         this.cancelChannel (clientName, channelName);
         out = $rh.createReply();
         break;
       }

       case 2:  // scs/event_service/ChannelManagement/notifyChannel
       {
         String channelName = in.read_string ();
         org.omg.CORBA.Any ev = scs.event_service.EventHelper.read (in);
         this.notifyChannel (channelName, ev);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:scs/event_service/ChannelManagement:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ChannelManagement _this() 
  {
    return ChannelManagementHelper.narrow(
    super._this_object());
  }

  public ChannelManagement _this(org.omg.CORBA.ORB orb) 
  {
    return ChannelManagementHelper.narrow(
    super._this_object(orb));
  }


} // class ChannelManagementPOA
