package scs.event_service;


/**
* scs/event_service/ChannelCollectionPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/events.idl
* Saturday, October 18, 2008 4:06:47 PM BRST
*/

public class ChannelCollectionPOATie extends ChannelCollectionPOA
{

  // Constructors

  public ChannelCollectionPOATie ( scs.event_service.ChannelCollectionOperations delegate ) {
      this._impl = delegate;
  }
  public ChannelCollectionPOATie ( scs.event_service.ChannelCollectionOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public scs.event_service.ChannelCollectionOperations _delegate() {
      return this._impl;
  }
  public void _delegate (scs.event_service.ChannelCollectionOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public scs.core.IComponent getChannel (String name)
  {
    return _impl.getChannel(name);
  } // getChannel

  public scs.event_service.ChannelDescr[] getAll ()
  {
    return _impl.getAll();
  } // getAll

  private scs.event_service.ChannelCollectionOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ChannelCollectionPOATie
