package scs.event_service;


/**
* scs/event_service/ChannelFactoryPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/events.idl
* Saturday, October 18, 2008 4:06:47 PM BRST
*/

public class ChannelFactoryPOATie extends ChannelFactoryPOA
{

  // Constructors

  public ChannelFactoryPOATie ( scs.event_service.ChannelFactoryOperations delegate ) {
      this._impl = delegate;
  }
  public ChannelFactoryPOATie ( scs.event_service.ChannelFactoryOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public scs.event_service.ChannelFactoryOperations _delegate() {
      return this._impl;
  }
  public void _delegate (scs.event_service.ChannelFactoryOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public scs.core.IComponent create (String name) throws scs.event_service.NameAlreadyInUse
  {
    return _impl.create(name);
  } // create

  public void destroy (String name) throws scs.event_service.InvalidName
  {
    _impl.destroy(name);
  } // destroy

  private scs.event_service.ChannelFactoryOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ChannelFactoryPOATie
