package scs.event_service;


/**
* scs/event_service/ChannelDescrHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/events.idl
* Saturday, October 18, 2008 4:06:47 PM BRST
*/

abstract public class ChannelDescrHelper
{
  private static String  _id = "IDL:scs/event_service/ChannelDescr:1.0";

  public static void insert (org.omg.CORBA.Any a, scs.event_service.ChannelDescr that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static scs.event_service.ChannelDescr extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "name",
            _tcOf_members0,
            null);
          _tcOf_members0 = scs.core.IComponentHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "channel",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (scs.event_service.ChannelDescrHelper.id (), "ChannelDescr", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static scs.event_service.ChannelDescr read (org.omg.CORBA.portable.InputStream istream)
  {
    scs.event_service.ChannelDescr value = new scs.event_service.ChannelDescr ();
    value.name = istream.read_string ();
    value.channel = scs.core.IComponentHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, scs.event_service.ChannelDescr value)
  {
    ostream.write_string (value.name);
    scs.core.IComponentHelper.write (ostream, value.channel);
  }

}
