package scs.event_service;


/**
* scs/event_service/ChannelManagementHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/events.idl
* Saturday, October 18, 2008 4:06:47 PM BRST
*/

abstract public class ChannelManagementHelper
{
  private static String  _id = "IDL:scs/event_service/ChannelManagement:1.0";

  public static void insert (org.omg.CORBA.Any a, scs.event_service.ChannelManagement that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static scs.event_service.ChannelManagement extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (scs.event_service.ChannelManagementHelper.id (), "ChannelManagement");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static scs.event_service.ChannelManagement read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ChannelManagementStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, scs.event_service.ChannelManagement value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static scs.event_service.ChannelManagement narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof scs.event_service.ChannelManagement)
      return (scs.event_service.ChannelManagement)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      scs.event_service._ChannelManagementStub stub = new scs.event_service._ChannelManagementStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static scs.event_service.ChannelManagement unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof scs.event_service.ChannelManagement)
      return (scs.event_service.ChannelManagement)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      scs.event_service._ChannelManagementStub stub = new scs.event_service._ChannelManagementStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
