package scs.event_service;

/**
* scs/event_service/InvalidNameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/events.idl
* Saturday, October 18, 2008 4:06:47 PM BRST
*/

public final class InvalidNameHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.event_service.InvalidName value = null;

  public InvalidNameHolder ()
  {
  }

  public InvalidNameHolder (scs.event_service.InvalidName initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.event_service.InvalidNameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.event_service.InvalidNameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.event_service.InvalidNameHelper.type ();
  }

}
