package scs.core;


/**
* scs/core/_IReceptaclesStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.idl
* Saturday, October 18, 2008 4:06:47 PM BRST
*/

public class _IReceptaclesStub extends org.omg.CORBA.portable.ObjectImpl implements scs.core.IReceptacles
{

  public int connect (String receptacle, org.omg.CORBA.Object obj) throws scs.core.InvalidName, scs.core.InvalidConnection, scs.core.AlreadyConnected, scs.core.ExceededConnectionLimit
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("connect", true);
                $out.write_string (receptacle);
                org.omg.CORBA.ObjectHelper.write ($out, obj);
                $in = _invoke ($out);
                int $result = scs.core.ConnectionIdHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:scs/core/InvalidName:1.0"))
                    throw scs.core.InvalidNameHelper.read ($in);
                else if (_id.equals ("IDL:scs/core/InvalidConnection:1.0"))
                    throw scs.core.InvalidConnectionHelper.read ($in);
                else if (_id.equals ("IDL:scs/core/AlreadyConnected:1.0"))
                    throw scs.core.AlreadyConnectedHelper.read ($in);
                else if (_id.equals ("IDL:scs/core/ExceededConnectionLimit:1.0"))
                    throw scs.core.ExceededConnectionLimitHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return connect (receptacle, obj        );
            } finally {
                _releaseReply ($in);
            }
  } // connect

  public void disconnect (int id) throws scs.core.InvalidConnection, scs.core.NoConnection
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("disconnect", true);
                scs.core.ConnectionIdHelper.write ($out, id);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:scs/core/InvalidConnection:1.0"))
                    throw scs.core.InvalidConnectionHelper.read ($in);
                else if (_id.equals ("IDL:scs/core/NoConnection:1.0"))
                    throw scs.core.NoConnectionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                disconnect (id        );
            } finally {
                _releaseReply ($in);
            }
  } // disconnect

  public scs.core.ConnectionDescription[] getConnections (String receptacle) throws scs.core.InvalidName
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getConnections", true);
                $out.write_string (receptacle);
                $in = _invoke ($out);
                scs.core.ConnectionDescription $result[] = scs.core.ConnectionDescriptionsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:scs/core/InvalidName:1.0"))
                    throw scs.core.InvalidNameHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getConnections (receptacle        );
            } finally {
                _releaseReply ($in);
            }
  } // getConnections

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:scs/core/IReceptacles:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _IReceptaclesStub
