package scs.core;


/**
* scs/core/ExceededConnectionLimit.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.idl
* Saturday, October 18, 2008 4:06:47 PM BRST
*/

public final class ExceededConnectionLimit extends org.omg.CORBA.UserException
{

  public ExceededConnectionLimit ()
  {
    super(ExceededConnectionLimitHelper.id());
  } // ctor


  public ExceededConnectionLimit (String $reason)
  {
    super(ExceededConnectionLimitHelper.id() + "  " + $reason);
  } // ctor

} // class ExceededConnectionLimit
