package scs.core;

/**
* scs/core/ExceededConnectionLimitHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.idl
* Saturday, October 18, 2008 4:06:47 PM BRST
*/

public final class ExceededConnectionLimitHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.core.ExceededConnectionLimit value = null;

  public ExceededConnectionLimitHolder ()
  {
  }

  public ExceededConnectionLimitHolder (scs.core.ExceededConnectionLimit initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.core.ExceededConnectionLimitHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.core.ExceededConnectionLimitHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.core.ExceededConnectionLimitHelper.type ();
  }

}
