package scs.core;


/**
* scs/core/IComponentPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.idl
* Saturday, October 18, 2008 4:06:47 PM BRST
*/

public class IComponentPOATie extends IComponentPOA
{

  // Constructors

  public IComponentPOATie ( scs.core.IComponentOperations delegate ) {
      this._impl = delegate;
  }
  public IComponentPOATie ( scs.core.IComponentOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public scs.core.IComponentOperations _delegate() {
      return this._impl;
  }
  public void _delegate (scs.core.IComponentOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void startup () throws scs.core.StartupFailed
  {
    _impl.startup();
  } // startup

  public void shutdown () throws scs.core.ShutdownFailed
  {
    _impl.shutdown();
  } // shutdown

  public org.omg.CORBA.Object getFacet (String facet_interface)
  {
    return _impl.getFacet(facet_interface);
  } // getFacet

  public org.omg.CORBA.Object getFacetByName (String facet)
  {
    return _impl.getFacetByName(facet);
  } // getFacetByName

  public scs.core.ComponentId getComponentId ()
  {
    return _impl.getComponentId();
  } // getComponentId

  private scs.core.IComponentOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class IComponentPOATie
