package scs.core;

/**
* scs/core/IComponentHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.idl
* Saturday, October 18, 2008 4:06:47 PM BRST
*/

public final class IComponentHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.core.IComponent value = null;

  public IComponentHolder ()
  {
  }

  public IComponentHolder (scs.core.IComponent initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.core.IComponentHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.core.IComponentHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.core.IComponentHelper.type ();
  }

}
