package scs.core;


/**
* scs/core/IMetaInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.idl
* Saturday, October 18, 2008 4:06:47 PM BRST
*/

public abstract class IMetaInterfacePOA extends org.omg.PortableServer.Servant
 implements scs.core.IMetaInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getFacets", new java.lang.Integer (0));
    _methods.put ("getFacetsByName", new java.lang.Integer (1));
    _methods.put ("getReceptacles", new java.lang.Integer (2));
    _methods.put ("getReceptaclesByName", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // scs/core/IMetaInterface/getFacets
       {
         scs.core.FacetDescription $result[] = null;
         $result = this.getFacets ();
         out = $rh.createReply();
         scs.core.FacetDescriptionsHelper.write (out, $result);
         break;
       }

       case 1:  // scs/core/IMetaInterface/getFacetsByName
       {
         try {
           String names[] = scs.core.NameListHelper.read (in);
           scs.core.FacetDescription $result[] = null;
           $result = this.getFacetsByName (names);
           out = $rh.createReply();
           scs.core.FacetDescriptionsHelper.write (out, $result);
         } catch (scs.core.InvalidName $ex) {
           out = $rh.createExceptionReply ();
           scs.core.InvalidNameHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // scs/core/IMetaInterface/getReceptacles
       {
         scs.core.ReceptacleDescription $result[] = null;
         $result = this.getReceptacles ();
         out = $rh.createReply();
         scs.core.ReceptacleDescriptionsHelper.write (out, $result);
         break;
       }

       case 3:  // scs/core/IMetaInterface/getReceptaclesByName
       {
         try {
           String names[] = scs.core.NameListHelper.read (in);
           scs.core.ReceptacleDescription $result[] = null;
           $result = this.getReceptaclesByName (names);
           out = $rh.createReply();
           scs.core.ReceptacleDescriptionsHelper.write (out, $result);
         } catch (scs.core.InvalidName $ex) {
           out = $rh.createExceptionReply ();
           scs.core.InvalidNameHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:scs/core/IMetaInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IMetaInterface _this() 
  {
    return IMetaInterfaceHelper.narrow(
    super._this_object());
  }

  public IMetaInterface _this(org.omg.CORBA.ORB orb) 
  {
    return IMetaInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class IMetaInterfacePOA
