package scs.core;

/**
* scs/core/InvalidNameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.idl
* Saturday, October 18, 2008 4:06:47 PM BRST
*/

public final class InvalidNameHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.core.InvalidName value = null;

  public InvalidNameHolder ()
  {
  }

  public InvalidNameHolder (scs.core.InvalidName initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.core.InvalidNameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.core.InvalidNameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.core.InvalidNameHelper.type ();
  }

}
