package scs.core;


/**
* scs/core/ReceptacleDescriptionsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.idl
* Saturday, October 18, 2008 4:06:47 PM BRST
*/

public final class ReceptacleDescriptionsHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.core.ReceptacleDescription value[] = null;

  public ReceptacleDescriptionsHolder ()
  {
  }

  public ReceptacleDescriptionsHolder (scs.core.ReceptacleDescription[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.core.ReceptacleDescriptionsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.core.ReceptacleDescriptionsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.core.ReceptacleDescriptionsHelper.type ();
  }

}
