package scs.core;


/**
* scs/core/StartupFailed.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.idl
* Saturday, October 18, 2008 4:06:47 PM BRST
*/

public final class StartupFailed extends org.omg.CORBA.UserException
{

  public StartupFailed ()
  {
    super(StartupFailedHelper.id());
  } // ctor


  public StartupFailed (String $reason)
  {
    super(StartupFailedHelper.id() + "  " + $reason);
  } // ctor

} // class StartupFailed
