package scs.demos.logmonitor;


/**
* scs/demos/logmonitor/LogMonitorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/logMonitor.idl
* Saturday, October 18, 2008 4:06:49 PM BRST
*/

public interface LogMonitorOperations 
{
  void setId (int identifier);
  int getId ();
  void ping ();
  void pong ();
  void start ();
  void stop ();
} // interface LogMonitorOperations
