package scs.demos.logmonitor;


/**
* scs/demos/logmonitor/LogMonitorPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/logMonitor.idl
* Saturday, October 18, 2008 4:06:49 PM BRST
*/

public class LogMonitorPOATie extends LogMonitorPOA
{

  // Constructors

  public LogMonitorPOATie ( scs.demos.logmonitor.LogMonitorOperations delegate ) {
      this._impl = delegate;
  }
  public LogMonitorPOATie ( scs.demos.logmonitor.LogMonitorOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public scs.demos.logmonitor.LogMonitorOperations _delegate() {
      return this._impl;
  }
  public void _delegate (scs.demos.logmonitor.LogMonitorOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void setId (int identifier)
  {
    _impl.setId(identifier);
  } // setId

  public int getId ()
  {
    return _impl.getId();
  } // getId

  public void ping ()
  {
    _impl.ping();
  } // ping

  public void pong ()
  {
    _impl.pong();
  } // pong

  public void start ()
  {
    _impl.start();
  } // start

  public void stop ()
  {
    _impl.stop();
  } // stop

  private scs.demos.logmonitor.LogMonitorOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class LogMonitorPOATie
