package scs.demos.logmonitor;


/**
* scs/demos/logmonitor/LogMonitorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/logMonitor.idl
* Saturday, October 18, 2008 4:06:49 PM BRST
*/

abstract public class LogMonitorHelper
{
  private static String  _id = "IDL:scs/demos/logmonitor/LogMonitor:1.0";

  public static void insert (org.omg.CORBA.Any a, scs.demos.logmonitor.LogMonitor that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static scs.demos.logmonitor.LogMonitor extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (scs.demos.logmonitor.LogMonitorHelper.id (), "LogMonitor");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static scs.demos.logmonitor.LogMonitor read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_LogMonitorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, scs.demos.logmonitor.LogMonitor value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static scs.demos.logmonitor.LogMonitor narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof scs.demos.logmonitor.LogMonitor)
      return (scs.demos.logmonitor.LogMonitor)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      scs.demos.logmonitor._LogMonitorStub stub = new scs.demos.logmonitor._LogMonitorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static scs.demos.logmonitor.LogMonitor unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof scs.demos.logmonitor.LogMonitor)
      return (scs.demos.logmonitor.LogMonitor)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      scs.demos.logmonitor._LogMonitorStub stub = new scs.demos.logmonitor._LogMonitorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
