package scs.demos.logmonitor;


/**
* scs/demos/logmonitor/LogMonitor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/logMonitor.idl
* Saturday, October 18, 2008 4:06:49 PM BRST
*/

public interface LogMonitor extends LogMonitorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LogMonitor
