package scs.reasoning;


/**
* scs/reasoning/BuildClassifierException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/reasoning.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public final class BuildClassifierException extends org.omg.CORBA.UserException
{

  public BuildClassifierException ()
  {
    super(BuildClassifierExceptionHelper.id());
  } // ctor


  public BuildClassifierException (String $reason)
  {
    super(BuildClassifierExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class BuildClassifierException
