package scs.reasoning;

/**
* scs/reasoning/DataCollectionFailureHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/reasoning.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public final class DataCollectionFailureHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.reasoning.DataCollectionFailure value = null;

  public DataCollectionFailureHolder ()
  {
  }

  public DataCollectionFailureHolder (scs.reasoning.DataCollectionFailure initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.reasoning.DataCollectionFailureHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.reasoning.DataCollectionFailureHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.reasoning.DataCollectionFailureHelper.type ();
  }

}
