package scs.reasoning;


/**
* scs/reasoning/FileReadingException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/reasoning.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public final class FileReadingException extends org.omg.CORBA.UserException
{

  public FileReadingException ()
  {
    super(FileReadingExceptionHelper.id());
  } // ctor


  public FileReadingException (String $reason)
  {
    super(FileReadingExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class FileReadingException
