package scs.reasoning;

/**
* scs/reasoning/MetricDescriptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/reasoning.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public final class MetricDescriptionHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.reasoning.MetricDescription value = null;

  public MetricDescriptionHolder ()
  {
  }

  public MetricDescriptionHolder (scs.reasoning.MetricDescription initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.reasoning.MetricDescriptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.reasoning.MetricDescriptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.reasoning.MetricDescriptionHelper.type ();
  }

}
