package scs.reasoning;


/**
* scs/reasoning/MonitorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/reasoning.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

abstract public class MonitorHelper
{
  private static String  _id = "IDL:scs/reasoning/Monitor:1.0";

  public static void insert (org.omg.CORBA.Any a, scs.reasoning.Monitor that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static scs.reasoning.Monitor extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (scs.reasoning.MonitorHelper.id (), "Monitor");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static scs.reasoning.Monitor read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MonitorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, scs.reasoning.Monitor value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static scs.reasoning.Monitor narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof scs.reasoning.Monitor)
      return (scs.reasoning.Monitor)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      scs.reasoning._MonitorStub stub = new scs.reasoning._MonitorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static scs.reasoning.Monitor unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof scs.reasoning.Monitor)
      return (scs.reasoning.Monitor)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      scs.reasoning._MonitorStub stub = new scs.reasoning._MonitorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
