package scs.reasoning;


/**
* scs/reasoning/ReasoningPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/reasoning.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public class ReasoningPOATie extends ReasoningPOA
{

  // Constructors

  public ReasoningPOATie ( scs.reasoning.ReasoningOperations delegate ) {
      this._impl = delegate;
  }
  public ReasoningPOATie ( scs.reasoning.ReasoningOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public scs.reasoning.ReasoningOperations _delegate() {
      return this._impl;
  }
  public void _delegate (scs.reasoning.ReasoningOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void buildModel (String fileName) throws scs.reasoning.BuildClassifierException
  {
    _impl.buildModel(fileName);
  } // buildModel

  public String adjudicator (String[] metricsToLabel)
  {
    return _impl.adjudicator(metricsToLabel);
  } // adjudicator

  private scs.reasoning.ReasoningOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ReasoningPOATie
