package scs.reasoning;


/**
* scs/reasoning/ReasoningOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/reasoning.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public interface ReasoningOperations 
{
  void buildModel (String fileName) throws scs.reasoning.BuildClassifierException;
  String adjudicator (String[] metricsToLabel);
} // interface ReasoningOperations
