package scs.reasoning;


/**
* scs/reasoning/SystemStateValueHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/reasoning.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

abstract public class SystemStateValueHelper
{
  private static String  _id = "IDL:scs/reasoning/SystemStateValue:1.0";

  public static void insert (org.omg.CORBA.Any a, scs.reasoning.SystemStateValue that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static scs.reasoning.SystemStateValue extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[0] = new org.omg.CORBA.StructMember (
            "compliance",
            _tcOf_members0,
            null);
          _tcOf_members0 = scs.reasoning.MetricDescriptionHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (scs.reasoning.MetricDescriptionSeqHelper.id (), "MetricDescriptionSeq", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "rootCause",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (scs.reasoning.SystemStateValueHelper.id (), "SystemStateValue", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static scs.reasoning.SystemStateValue read (org.omg.CORBA.portable.InputStream istream)
  {
    scs.reasoning.SystemStateValue value = new scs.reasoning.SystemStateValue ();
    value.compliance = istream.read_boolean ();
    value.rootCause = scs.reasoning.MetricDescriptionSeqHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, scs.reasoning.SystemStateValue value)
  {
    ostream.write_boolean (value.compliance);
    scs.reasoning.MetricDescriptionSeqHelper.write (ostream, value.rootCause);
  }

}
