/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class system_SystemInformation_NegativeCPUTime */

#ifndef _Included_system_SystemInformation_NegativeCPUTime
#define _Included_system_SystemInformation_NegativeCPUTime
#ifdef __cplusplus
extern "C" {
#endif
#undef system_SystemInformation_NegativeCPUTime_serialVersionUID
#define system_SystemInformation_NegativeCPUTime_serialVersionUID -3042686055658047285LL
#undef system_SystemInformation_NegativeCPUTime_serialVersionUID
#define system_SystemInformation_NegativeCPUTime_serialVersionUID -3387516993124229948LL
#undef system_SystemInformation_NegativeCPUTime_serialVersionUID
#define system_SystemInformation_NegativeCPUTime_serialVersionUID 1LL
#ifdef __cplusplus
}
#endif
#endif
