/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class system_SystemInformation_NetworkStats */

#ifndef _Included_system_SystemInformation_NetworkStats
#define _Included_system_SystemInformation_NetworkStats
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
