package scs.container;

/**
* scs/container/ComponentSuspensionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public final class ComponentSuspensionHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.container.ComponentSuspension value = null;

  public ComponentSuspensionHolder ()
  {
  }

  public ComponentSuspensionHolder (scs.container.ComponentSuspension initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.container.ComponentSuspensionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.container.ComponentSuspensionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.container.ComponentSuspensionHelper.type ();
  }

}
