package scs.container;


/**
* scs/container/ComponentSuspensionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public abstract class ComponentSuspensionPOA extends org.omg.PortableServer.Servant
 implements scs.container.ComponentSuspensionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("suspend", new java.lang.Integer (0));
    _methods.put ("halt", new java.lang.Integer (1));
    _methods.put ("resume", new java.lang.Integer (2));
    _methods.put ("getStatus", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // a negative number means a suspension (yields coroutines)
       case 0:  // scs/container/ComponentSuspension/suspend
       {
         this.suspend ();
         out = $rh.createReply();
         break;
       }

       case 1:  // scs/container/ComponentSuspension/halt
       {
         this.halt ();
         out = $rh.createReply();
         break;
       }

       case 2:  // scs/container/ComponentSuspension/resume
       {
         this.resume ();
         out = $rh.createReply();
         break;
       }

       case 3:  // scs/container/ComponentSuspension/getStatus
       {
         int $result = (int)0;
         $result = this.getStatus ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:scs/container/ComponentSuspension:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ComponentSuspension _this() 
  {
    return ComponentSuspensionHelper.narrow(
    super._this_object());
  }

  public ComponentSuspension _this(org.omg.CORBA.ORB orb) 
  {
    return ComponentSuspensionHelper.narrow(
    super._this_object(orb));
  }


} // class ComponentSuspensionPOA
