package scs.container;


/**
* scs/container/ComponentLoaderPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public class ComponentLoaderPOATie extends ComponentLoaderPOA
{

  // Constructors

  public ComponentLoaderPOATie ( scs.container.ComponentLoaderOperations delegate ) {
      this._impl = delegate;
  }
  public ComponentLoaderPOATie ( scs.container.ComponentLoaderOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public scs.container.ComponentLoaderOperations _delegate() {
      return this._impl;
  }
  public void _delegate (scs.container.ComponentLoaderOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public scs.container.ComponentHandle load (scs.core.ComponentId id, String[] args) throws scs.container.ComponentNotFound, scs.container.ComponentAlreadyLoaded, scs.container.LoadFailure
  {
    return _impl.load(id, args);
  } // load

  public void unload (scs.container.ComponentHandle handle) throws scs.container.ComponentNotFound
  {
    _impl.unload(handle);
  } // unload

  public scs.core.ComponentId[] getInstalledComponents ()
  {
    return _impl.getInstalledComponents();
  } // getInstalledComponents

  private scs.container.ComponentLoaderOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ComponentLoaderPOATie
