package scs.container;


/**
* scs/container/ComponentHandleSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public final class ComponentHandleSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.container.ComponentHandle value[] = null;

  public ComponentHandleSeqHolder ()
  {
  }

  public ComponentHandleSeqHolder (scs.container.ComponentHandle[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.container.ComponentHandleSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.container.ComponentHandleSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.container.ComponentHandleSeqHelper.type ();
  }

}
