package scs.container;

/**
* scs/container/ComponentNotFoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public final class ComponentNotFoundHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.container.ComponentNotFound value = null;

  public ComponentNotFoundHolder ()
  {
  }

  public ComponentNotFoundHolder (scs.container.ComponentNotFound initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.container.ComponentNotFoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.container.ComponentNotFoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.container.ComponentNotFoundHelper.type ();
  }

}
