package scs.container;

/**
* scs/container/ComponentInterceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public final class ComponentInterceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.container.ComponentInterception value = null;

  public ComponentInterceptionHolder ()
  {
  }

  public ComponentInterceptionHolder (scs.container.ComponentInterception initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.container.ComponentInterceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.container.ComponentInterceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.container.ComponentInterceptionHelper.type ();
  }

}
