package scs.container;

/**
* scs/container/ComponentCollectionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public final class ComponentCollectionHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.container.ComponentCollection value = null;

  public ComponentCollectionHolder ()
  {
  }

  public ComponentCollectionHolder (scs.container.ComponentCollection initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.container.ComponentCollectionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.container.ComponentCollectionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.container.ComponentCollectionHelper.type ();
  }

}
