package scs.container;


/**
* scs/container/ComponentSuspensionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public interface ComponentSuspensionOperations 
{

  // a negative number means a suspension (yields coroutines)
  void suspend ();
  void halt ();
  void resume ();
  int getStatus ();
} // interface ComponentSuspensionOperations
