package scs.container;


/**
* scs/container/ComponentCollectionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public abstract class ComponentCollectionPOA extends org.omg.PortableServer.Servant
 implements scs.container.ComponentCollectionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getComponent", new java.lang.Integer (0));
    _methods.put ("getComponents", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // scs/container/ComponentCollection/getComponent
       {
         scs.core.ComponentId id = scs.core.ComponentIdHelper.read (in);
         scs.container.ComponentHandle $result[] = null;
         $result = this.getComponent (id);
         out = $rh.createReply();
         scs.container.ComponentHandleSeqHelper.write (out, $result);
         break;
       }

       case 1:  // scs/container/ComponentCollection/getComponents
       {
         scs.container.ComponentHandle $result[] = null;
         $result = this.getComponents ();
         out = $rh.createReply();
         scs.container.ComponentHandleSeqHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:scs/container/ComponentCollection:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ComponentCollection _this() 
  {
    return ComponentCollectionHelper.narrow(
    super._this_object());
  }

  public ComponentCollection _this(org.omg.CORBA.ORB orb) 
  {
    return ComponentCollectionHelper.narrow(
    super._this_object(orb));
  }


} // class ComponentCollectionPOA
