package scs.container;


/**
* scs/container/ComponentInterceptionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

abstract public class ComponentInterceptionHelper
{
  private static String  _id = "IDL:scs/container/ComponentInterception:1.0";

  public static void insert (org.omg.CORBA.Any a, scs.container.ComponentInterception that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static scs.container.ComponentInterception extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (scs.container.ComponentInterceptionHelper.id (), "ComponentInterception");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static scs.container.ComponentInterception read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ComponentInterceptionStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, scs.container.ComponentInterception value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static scs.container.ComponentInterception narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof scs.container.ComponentInterception)
      return (scs.container.ComponentInterception)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      scs.container._ComponentInterceptionStub stub = new scs.container._ComponentInterceptionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static scs.container.ComponentInterception unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof scs.container.ComponentInterception)
      return (scs.container.ComponentInterception)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      scs.container._ComponentInterceptionStub stub = new scs.container._ComponentInterceptionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
