package scs.container;

/**
* scs/container/ListLockFailHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public final class ListLockFailHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.container.ListLockFail value = null;

  public ListLockFailHolder ()
  {
  }

  public ListLockFailHolder (scs.container.ListLockFail initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.container.ListLockFailHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.container.ListLockFailHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.container.ListLockFailHelper.type ();
  }

}
