package scs.container;


/**
* scs/container/OctetSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public final class OctetSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public OctetSeqHolder ()
  {
  }

  public OctetSeqHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.container.OctetSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.container.OctetSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.container.OctetSeqHelper.type ();
  }

}
