package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/_IOFormatStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Saturday, October 18, 2008 4:06:50 PM BRST
*/


//Descreve a entrada-saida do processo mapreduce
public class _IOFormatStub extends org.omg.CORBA.portable.ObjectImpl implements scs.demos.mapreduce.IOFormat
{

  public scs.demos.mapreduce.RecordReader getRecordReader (scs.demos.mapreduce.TaskStatus status) throws scs.demos.mapreduce.IOFormatException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRecordReader", true);
                scs.demos.mapreduce.TaskStatusHelper.write ($out, status);
                $in = _invoke ($out);
                scs.demos.mapreduce.RecordReader $result = scs.demos.mapreduce.RecordReaderHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:scs/demos/mapreduce/IOFormatException:1.0"))
                    throw scs.demos.mapreduce.IOFormatExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRecordReader (status        );
            } finally {
                _releaseReply ($in);
            }
  } // getRecordReader

  public scs.demos.mapreduce.RecordWriter getRecordWriter (scs.demos.mapreduce.TaskStatus status) throws scs.demos.mapreduce.IOFormatException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRecordWriter", true);
                scs.demos.mapreduce.TaskStatusHelper.write ($out, status);
                $in = _invoke ($out);
                scs.demos.mapreduce.RecordWriter $result = scs.demos.mapreduce.RecordWriterHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:scs/demos/mapreduce/IOFormatException:1.0"))
                    throw scs.demos.mapreduce.IOFormatExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRecordWriter (status        );
            } finally {
                _releaseReply ($in);
            }
  } // getRecordWriter

  public scs.demos.mapreduce.FileSplit[] getSplits (String confFileName, scs.demos.mapreduce.Reporter reporter) throws scs.demos.mapreduce.SplitException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getSplits", true);
                $out.write_string (confFileName);
                scs.demos.mapreduce.ReporterHelper.write ($out, reporter);
                $in = _invoke ($out);
                scs.demos.mapreduce.FileSplit $result[] = scs.demos.mapreduce.FileSplitsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:scs/demos/mapreduce/SplitException:1.0"))
                    throw scs.demos.mapreduce.SplitExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getSplits (confFileName, reporter        );
            } finally {
                _releaseReply ($in);
            }
  } // getSplits

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:scs/demos/mapreduce/IOFormat:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _IOFormatStub
