package scs.demos.mapreduce;

/**
* scs/demos/mapreduce/FileSplitHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Saturday, October 18, 2008 4:06:50 PM BRST
*/


// Representa uma particao do arquivo de entrada
public final class FileSplitHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.demos.mapreduce.FileSplit value = null;

  public FileSplitHolder ()
  {
  }

  public FileSplitHolder (scs.demos.mapreduce.FileSplit initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.demos.mapreduce.FileSplitHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.demos.mapreduce.FileSplitHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.demos.mapreduce.FileSplitHelper.type ();
  }

}
