package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/FileSplit.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Saturday, October 18, 2008 4:06:50 PM BRST
*/


// Representa uma particao do arquivo de entrada
public interface FileSplit extends FileSplitOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileSplit
