package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/IOFormat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Saturday, October 18, 2008 4:06:50 PM BRST
*/


//Descreve a entrada-saida do processo mapreduce
public interface IOFormat extends IOFormatOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IOFormat
