package scs.demos.mapreduce;

/**
* scs/demos/mapreduce/IOFormatHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Saturday, October 18, 2008 4:06:50 PM BRST
*/


//Descreve a entrada-saida do processo mapreduce
public final class IOFormatHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.demos.mapreduce.IOFormat value = null;

  public IOFormatHolder ()
  {
  }

  public IOFormatHolder (scs.demos.mapreduce.IOFormat initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.demos.mapreduce.IOFormatHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.demos.mapreduce.IOFormatHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.demos.mapreduce.IOFormatHelper.type ();
  }

}
