package scs.demos.mapreduce;

/**
* scs/demos/mapreduce/MapperHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Saturday, October 18, 2008 4:06:50 PM BRST
*/


// Define a operacao map
public final class MapperHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.demos.mapreduce.Mapper value = null;

  public MapperHolder ()
  {
  }

  public MapperHolder (scs.demos.mapreduce.Mapper initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.demos.mapreduce.MapperHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.demos.mapreduce.MapperHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.demos.mapreduce.MapperHelper.type ();
  }

}
