package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/MasterPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Saturday, October 18, 2008 4:06:50 PM BRST
*/

public class MasterPOATie extends MasterPOA
{

  // Constructors

  public MasterPOATie ( scs.demos.mapreduce.MasterOperations delegate ) {
      this._impl = delegate;
  }
  public MasterPOATie ( scs.demos.mapreduce.MasterOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public scs.demos.mapreduce.MasterOperations _delegate() {
      return this._impl;
  }
  public void _delegate (scs.demos.mapreduce.MasterOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void start (String confFileName, scs.demos.mapreduce.Reporter reporter) throws scs.demos.mapreduce.PropertiesException, scs.demos.mapreduce.ConectionToExecNodesException, scs.demos.mapreduce.ChannelException, scs.demos.mapreduce.WorkerInstantiationException, scs.demos.mapreduce.TaskInstantiationException, scs.demos.mapreduce.StartFailureException
  {
    _impl.start(confFileName, reporter);
  } // start

  private scs.demos.mapreduce.MasterOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class MasterPOATie
