package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/MasterPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Saturday, October 18, 2008 4:06:50 PM BRST
*/

public abstract class MasterPOA extends org.omg.PortableServer.Servant
 implements scs.demos.mapreduce.MasterOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("start", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // scs/demos/mapreduce/Master/start
       {
         try {
           String confFileName = in.read_string ();
           scs.demos.mapreduce.Reporter reporter = scs.demos.mapreduce.ReporterHelper.read (in);
           this.start (confFileName, reporter);
           out = $rh.createReply();
         } catch (scs.demos.mapreduce.PropertiesException $ex) {
           out = $rh.createExceptionReply ();
           scs.demos.mapreduce.PropertiesExceptionHelper.write (out, $ex);
         } catch (scs.demos.mapreduce.ConectionToExecNodesException $ex) {
           out = $rh.createExceptionReply ();
           scs.demos.mapreduce.ConectionToExecNodesExceptionHelper.write (out, $ex);
         } catch (scs.demos.mapreduce.ChannelException $ex) {
           out = $rh.createExceptionReply ();
           scs.demos.mapreduce.ChannelExceptionHelper.write (out, $ex);
         } catch (scs.demos.mapreduce.WorkerInstantiationException $ex) {
           out = $rh.createExceptionReply ();
           scs.demos.mapreduce.WorkerInstantiationExceptionHelper.write (out, $ex);
         } catch (scs.demos.mapreduce.TaskInstantiationException $ex) {
           out = $rh.createExceptionReply ();
           scs.demos.mapreduce.TaskInstantiationExceptionHelper.write (out, $ex);
         } catch (scs.demos.mapreduce.StartFailureException $ex) {
           out = $rh.createExceptionReply ();
           scs.demos.mapreduce.StartFailureExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:scs/demos/mapreduce/Master:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Master _this() 
  {
    return MasterHelper.narrow(
    super._this_object());
  }

  public Master _this(org.omg.CORBA.ORB orb) 
  {
    return MasterHelper.narrow(
    super._this_object(orb));
  }


} // class MasterPOA
