package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/OutputCollector.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Saturday, October 18, 2008 4:06:50 PM BRST
*/


//Usado por mappers and reducers para emitir pares <key,value> intermediarios
public interface OutputCollector extends OutputCollectorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface OutputCollector
