package scs.demos.mapreduce;

/**
* scs/demos/mapreduce/PartitionerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Saturday, October 18, 2008 4:06:50 PM BRST
*/


//Define a operacao para distribuir chaves para os reducers
public final class PartitionerHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.demos.mapreduce.Partitioner value = null;

  public PartitionerHolder ()
  {
  }

  public PartitionerHolder (scs.demos.mapreduce.Partitioner initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.demos.mapreduce.PartitionerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.demos.mapreduce.PartitionerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.demos.mapreduce.PartitionerHelper.type ();
  }

}
