package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/PartitionerPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Saturday, October 18, 2008 4:06:50 PM BRST
*/


//Define a operacao para distribuir chaves para os reducers
public class PartitionerPOATie extends PartitionerPOA
{

  // Constructors

  public PartitionerPOATie ( scs.demos.mapreduce.PartitionerOperations delegate ) {
      this._impl = delegate;
  }
  public PartitionerPOATie ( scs.demos.mapreduce.PartitionerOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public scs.demos.mapreduce.PartitionerOperations _delegate() {
      return this._impl;
  }
  public void _delegate (scs.demos.mapreduce.PartitionerOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public int getPartition (org.omg.CORBA.Any key, org.omg.CORBA.Any value, int numPartitions)
  {
    return _impl.getPartition(key, value, numPartitions);
  } // getPartition

  private scs.demos.mapreduce.PartitionerOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class PartitionerPOATie
