package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/PartitionerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Saturday, October 18, 2008 4:06:50 PM BRST
*/


//Define a operacao para distribuir chaves para os reducers
public interface PartitionerOperations 
{
  int getPartition (org.omg.CORBA.Any key, org.omg.CORBA.Any value, int numPartitions);
} // interface PartitionerOperations
