package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/PropertiesException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Saturday, October 18, 2008 4:06:50 PM BRST
*/

public final class PropertiesException extends org.omg.CORBA.UserException
{

  public PropertiesException ()
  {
    super(PropertiesExceptionHelper.id());
  } // ctor


  public PropertiesException (String $reason)
  {
    super(PropertiesExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class PropertiesException
