package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/Reducer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Saturday, October 18, 2008 4:06:50 PM BRST
*/


// Define a operacao reduce
public interface Reducer extends ReducerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Reducer
