package scs.demos.mapreduce;

/**
* scs/demos/mapreduce/ReporterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Saturday, October 18, 2008 4:06:50 PM BRST
*/


//Reporta log de mensagens de operacoes
public final class ReporterHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.demos.mapreduce.Reporter value = null;

  public ReporterHolder ()
  {
  }

  public ReporterHolder (scs.demos.mapreduce.Reporter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.demos.mapreduce.ReporterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.demos.mapreduce.ReporterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.demos.mapreduce.ReporterHelper.type ();
  }

}
