package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/ReporterPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Saturday, October 18, 2008 4:06:50 PM BRST
*/


//Reporta log de mensagens de operacoes
public class ReporterPOATie extends ReporterPOA
{

  // Constructors

  public ReporterPOATie ( scs.demos.mapreduce.ReporterOperations delegate ) {
      this._impl = delegate;
  }
  public ReporterPOATie ( scs.demos.mapreduce.ReporterOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public scs.demos.mapreduce.ReporterOperations _delegate() {
      return this._impl;
  }
  public void _delegate (scs.demos.mapreduce.ReporterOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public boolean open ()
  {
    return _impl.open();
  } // open

  public void report (int level, String message)
  {
    _impl.report(level, message);
  } // report

  public void close ()
  {
    _impl.close();
  } // close

  private scs.demos.mapreduce.ReporterOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ReporterPOATie
