package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/ReporterPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Saturday, October 18, 2008 4:06:50 PM BRST
*/


//Reporta log de mensagens de operacoes
public abstract class ReporterPOA extends org.omg.PortableServer.Servant
 implements scs.demos.mapreduce.ReporterOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("open", new java.lang.Integer (0));
    _methods.put ("report", new java.lang.Integer (1));
    _methods.put ("close", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // scs/demos/mapreduce/Reporter/open
       {
         boolean $result = false;
         $result = this.open ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // scs/demos/mapreduce/Reporter/report
       {
         int level = in.read_long ();
         String message = in.read_string ();
         this.report (level, message);
         out = $rh.createReply();
         break;
       }

       case 2:  // scs/demos/mapreduce/Reporter/close
       {
         this.close ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:scs/demos/mapreduce/Reporter:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Reporter _this() 
  {
    return ReporterHelper.narrow(
    super._this_object());
  }

  public Reporter _this(org.omg.CORBA.ORB orb) 
  {
    return ReporterHelper.narrow(
    super._this_object(orb));
  }


} // class ReporterPOA
