package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/SplitException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Saturday, October 18, 2008 4:06:50 PM BRST
*/

public final class SplitException extends org.omg.CORBA.UserException
{

  public SplitException ()
  {
    super(SplitExceptionHelper.id());
  } // ctor


  public SplitException (String $reason)
  {
    super(SplitExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class SplitException
