package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/TaskStatusHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Saturday, October 18, 2008 4:06:50 PM BRST
*/

abstract public class TaskStatusHelper
{
  private static String  _id = "IDL:scs/demos/mapreduce/TaskStatus:1.0";

  public static void insert (org.omg.CORBA.Any a, scs.demos.mapreduce.TaskStatus that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static scs.demos.mapreduce.TaskStatus extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (scs.demos.mapreduce.TaskStatusHelper.id (), "TaskStatus", new String[] { "MAP", "REDUCE", "ERROR", "END"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static scs.demos.mapreduce.TaskStatus read (org.omg.CORBA.portable.InputStream istream)
  {
    return scs.demos.mapreduce.TaskStatus.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, scs.demos.mapreduce.TaskStatus value)
  {
    ostream.write_long (value.value ());
  }

}
