package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/TaskHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Saturday, October 18, 2008 4:06:50 PM BRST
*/

abstract public class TaskHelper
{
  private static String  _id = "IDL:scs/demos/mapreduce/Task:1.0";

  public static void insert (org.omg.CORBA.Any a, scs.demos.mapreduce.Task that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static scs.demos.mapreduce.Task extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (scs.demos.mapreduce.TaskHelper.id (), "Task");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static scs.demos.mapreduce.Task read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_TaskStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, scs.demos.mapreduce.Task value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static scs.demos.mapreduce.Task narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof scs.demos.mapreduce.Task)
      return (scs.demos.mapreduce.Task)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      scs.demos.mapreduce._TaskStub stub = new scs.demos.mapreduce._TaskStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static scs.demos.mapreduce.Task unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof scs.demos.mapreduce.Task)
      return (scs.demos.mapreduce.Task)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      scs.demos.mapreduce._TaskStub stub = new scs.demos.mapreduce._TaskStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
