package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/TaskStatus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Saturday, October 18, 2008 4:06:50 PM BRST
*/

public class TaskStatus implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static scs.demos.mapreduce.TaskStatus[] __array = new scs.demos.mapreduce.TaskStatus [__size];

  public static final int _MAP = 0;
  public static final scs.demos.mapreduce.TaskStatus MAP = new scs.demos.mapreduce.TaskStatus(_MAP);
  public static final int _REDUCE = 1;
  public static final scs.demos.mapreduce.TaskStatus REDUCE = new scs.demos.mapreduce.TaskStatus(_REDUCE);
  public static final int _ERROR = 2;
  public static final scs.demos.mapreduce.TaskStatus ERROR = new scs.demos.mapreduce.TaskStatus(_ERROR);
  public static final int _END = 3;
  public static final scs.demos.mapreduce.TaskStatus END = new scs.demos.mapreduce.TaskStatus(_END);

  public int value ()
  {
    return __value;
  }

  public static scs.demos.mapreduce.TaskStatus from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected TaskStatus (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class TaskStatus
