package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/TaskPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Saturday, October 18, 2008 4:06:50 PM BRST
*/

public class TaskPOATie extends TaskPOA
{

  // Constructors

  public TaskPOATie ( scs.demos.mapreduce.TaskOperations delegate ) {
      this._impl = delegate;
  }
  public TaskPOATie ( scs.demos.mapreduce.TaskOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public scs.demos.mapreduce.TaskOperations _delegate() {
      return this._impl;
  }
  public void _delegate (scs.demos.mapreduce.TaskOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public int getId ()
  {
    return _impl.getId();
  } // getId

  public void setStatus (scs.demos.mapreduce.TaskStatus status)
  {
    _impl.setStatus(status);
  } // setStatus

  public scs.demos.mapreduce.TaskStatus getStatus ()
  {
    return _impl.getStatus();
  } // getStatus

  public scs.demos.mapreduce.FileSplit[] getInput ()
  {
    return _impl.getInput();
  } // getInput

  public scs.demos.mapreduce.FileSplit[] getOutput ()
  {
    return _impl.getOutput();
  } // getOutput

  public scs.demos.mapreduce.Reporter getReporter ()
  {
    return _impl.getReporter();
  } // getReporter

  public void run () throws scs.demos.mapreduce.IOMapReduceException
  {
    _impl.run();
  } // run

  private scs.demos.mapreduce.TaskOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class TaskPOATie
