module scs{
	module demos{
		module logmonitor {
			interface LogMonitor {
				void setId(in long identifier);
				long getId();
			  	void publishLog(in any logMessage);
			};
			interface EventSink {
				void push(in any event);
				void disconnect();
			};
			interface LogViewer {
				void setId(in long identifier);
				long getId();
			};
		};
	};
};