package scs.auxiliar;


/**
* scs/auxiliar/ComponentPropertiesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public interface ComponentPropertiesOperations 
{
  void setProperty (scs.execution_node.Property property) throws scs.auxiliar.ReadOnlyProperty;
  scs.execution_node.Property getProperty (String name) throws scs.auxiliar.UndefinedProperty;
  scs.execution_node.Property[] getProperties ();
} // interface ComponentPropertiesOperations
