package scs.auxiliar;


/**
* scs/auxiliar/ComponentPropertiesPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public abstract class ComponentPropertiesPOA extends org.omg.PortableServer.Servant
 implements scs.auxiliar.ComponentPropertiesOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("setProperty", new java.lang.Integer (0));
    _methods.put ("getProperty", new java.lang.Integer (1));
    _methods.put ("getProperties", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // scs/auxiliar/ComponentProperties/setProperty
       {
         try {
           scs.execution_node.Property property = scs.execution_node.PropertyHelper.read (in);
           this.setProperty (property);
           out = $rh.createReply();
         } catch (scs.auxiliar.ReadOnlyProperty $ex) {
           out = $rh.createExceptionReply ();
           scs.auxiliar.ReadOnlyPropertyHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // scs/auxiliar/ComponentProperties/getProperty
       {
         try {
           String name = in.read_string ();
           scs.execution_node.Property $result = null;
           $result = this.getProperty (name);
           out = $rh.createReply();
           scs.execution_node.PropertyHelper.write (out, $result);
         } catch (scs.auxiliar.UndefinedProperty $ex) {
           out = $rh.createExceptionReply ();
           scs.auxiliar.UndefinedPropertyHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // scs/auxiliar/ComponentProperties/getProperties
       {
         scs.execution_node.Property $result[] = null;
         $result = this.getProperties ();
         out = $rh.createReply();
         scs.execution_node.PropertySeqHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:scs/auxiliar/ComponentProperties:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ComponentProperties _this() 
  {
    return ComponentPropertiesHelper.narrow(
    super._this_object());
  }

  public ComponentProperties _this(org.omg.CORBA.ORB orb) 
  {
    return ComponentPropertiesHelper.narrow(
    super._this_object(orb));
  }


} // class ComponentPropertiesPOA
