package scs.auxiliar;


/**
* scs/auxiliar/ComponentHelpPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public class ComponentHelpPOATie extends ComponentHelpPOA
{

  // Constructors

  public ComponentHelpPOATie ( scs.auxiliar.ComponentHelpOperations delegate ) {
      this._impl = delegate;
  }
  public ComponentHelpPOATie ( scs.auxiliar.ComponentHelpOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public scs.auxiliar.ComponentHelpOperations _delegate() {
      return this._impl;
  }
  public void _delegate (scs.auxiliar.ComponentHelpOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public String getHelpInfo (scs.core.ComponentId id) throws scs.container.ComponentNotFound, scs.auxiliar.HelpInfoNotAvailable
  {
    return _impl.getHelpInfo(id);
  } // getHelpInfo

  private scs.auxiliar.ComponentHelpOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ComponentHelpPOATie
