package scs.auxiliar;


/**
* scs/auxiliar/ComponentHelpPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public abstract class ComponentHelpPOA extends org.omg.PortableServer.Servant
 implements scs.auxiliar.ComponentHelpOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getHelpInfo", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // scs/auxiliar/ComponentHelp/getHelpInfo
       {
         try {
           scs.core.ComponentId id = scs.core.ComponentIdHelper.read (in);
           String $result = null;
           $result = this.getHelpInfo (id);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (scs.container.ComponentNotFound $ex) {
           out = $rh.createExceptionReply ();
           scs.container.ComponentNotFoundHelper.write (out, $ex);
         } catch (scs.auxiliar.HelpInfoNotAvailable $ex) {
           out = $rh.createExceptionReply ();
           scs.auxiliar.HelpInfoNotAvailableHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:scs/auxiliar/ComponentHelp:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ComponentHelp _this() 
  {
    return ComponentHelpHelper.narrow(
    super._this_object());
  }

  public ComponentHelp _this(org.omg.CORBA.ORB orb) 
  {
    return ComponentHelpHelper.narrow(
    super._this_object(orb));
  }


} // class ComponentHelpPOA
