package scs.auxiliar;


/**
* scs/auxiliar/HelpInfoNotAvailable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public final class HelpInfoNotAvailable extends org.omg.CORBA.UserException
{

  public HelpInfoNotAvailable ()
  {
    super(HelpInfoNotAvailableHelper.id());
  } // ctor


  public HelpInfoNotAvailable (String $reason)
  {
    super(HelpInfoNotAvailableHelper.id() + "  " + $reason);
  } // ctor

} // class HelpInfoNotAvailable
