package scs.auxiliar;

/**
* scs/auxiliar/ReadOnlyPropertyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public final class ReadOnlyPropertyHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.auxiliar.ReadOnlyProperty value = null;

  public ReadOnlyPropertyHolder ()
  {
  }

  public ReadOnlyPropertyHolder (scs.auxiliar.ReadOnlyProperty initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.auxiliar.ReadOnlyPropertyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.auxiliar.ReadOnlyPropertyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.auxiliar.ReadOnlyPropertyHelper.type ();
  }

}
