package scs.execution_node;


/**
* scs/execution_node/ContainerDescription.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public final class ContainerDescription implements org.omg.CORBA.portable.IDLEntity
{
  public scs.core.IComponent container = null;
  public String container_name = null;
  public scs.core.IComponent execution_node = null;

  public ContainerDescription ()
  {
  } // ctor

  public ContainerDescription (scs.core.IComponent _container, String _container_name, scs.core.IComponent _execution_node)
  {
    container = _container;
    container_name = _container_name;
    execution_node = _execution_node;
  } // ctor

} // class ContainerDescription
