package scs.execution_node;


/**
* scs/execution_node/ContainerManagerPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public class ContainerManagerPOATie extends ContainerManagerPOA
{

  // Constructors

  public ContainerManagerPOATie ( scs.execution_node.ContainerManagerOperations delegate ) {
      this._impl = delegate;
  }
  public ContainerManagerPOATie ( scs.execution_node.ContainerManagerOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public scs.execution_node.ContainerManagerOperations _delegate() {
      return this._impl;
  }
  public void _delegate (scs.execution_node.ContainerManagerOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void registerContainer (String name, scs.core.IComponent ctr) throws scs.execution_node.ContainerAlreadyExists, scs.execution_node.InvalidContainer
  {
    _impl.registerContainer(name, ctr);
  } // registerContainer

  public void unregisterContainer (String name) throws scs.core.InvalidName
  {
    _impl.unregisterContainer(name);
  } // unregisterContainer

  private scs.execution_node.ContainerManagerOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ContainerManagerPOATie
