package scs.execution_node;

/**
* scs/execution_node/ContainerManagerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public final class ContainerManagerHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.execution_node.ContainerManager value = null;

  public ContainerManagerHolder ()
  {
  }

  public ContainerManagerHolder (scs.execution_node.ContainerManager initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.execution_node.ContainerManagerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.execution_node.ContainerManagerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.execution_node.ContainerManagerHelper.type ();
  }

}
