package scs.execution_node;


/**
* scs/execution_node/InvalidContainer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public final class InvalidContainer extends org.omg.CORBA.UserException
{

  public InvalidContainer ()
  {
    super(InvalidContainerHelper.id());
  } // ctor


  public InvalidContainer (String $reason)
  {
    super(InvalidContainerHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidContainer
