package scs.execution_node;


/**
* scs/execution_node/Property.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Saturday, October 18, 2008 4:06:48 PM BRST
*/

public final class Property implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String value = null;
  public boolean read_only = false;

  public Property ()
  {
  } // ctor

  public Property (String _name, String _value, boolean _read_only)
  {
    name = _name;
    value = _value;
    read_only = _read_only;
  } // ctor

} // class Property
